// If you already have your settings.gradle, please insert this configuration to the appropriate places.

include "common"
project (":common").projectDir = file("common")

include "TestSample"
project (":TestSample").projectDir = file("TestSample")

include "TestSample2"
project (":TestSample2").projectDir = file("TestSample2")

include "TestSample2:iflow-Join_Merge"
project (":TestSample2:iflow-Join_Merge").projectDir = file("TestSample2/IntegrationFlow/Join_Merge")

include "TestSample2:iflow-Lip_Test"
project (":TestSample2:iflow-Lip_Test").projectDir = file("TestSample2/IntegrationFlow/Lip_Test")

include "TestSample2:iflow-Namespace_Property_Lock"
project (":TestSample2:iflow-Namespace_Property_Lock").projectDir = file("TestSample2/IntegrationFlow/Namespace_Property_Lock")

include "TestSample2:iflow-Gather_Splitter"
project (":TestSample2:iflow-Gather_Splitter").projectDir = file("TestSample2/IntegrationFlow/Gather_Splitter")

include "TestSample2:iflow-ContentModifier3"
project (":TestSample2:iflow-ContentModifier3").projectDir = file("TestSample2/IntegrationFlow/ContentModifier3")

include "TestSample2:iflow-Converter_JSON"
project (":TestSample2:iflow-Converter_JSON").projectDir = file("TestSample2/IntegrationFlow/Converter_JSON")

include "TestSample2:iflow-Multicasting"
project (":TestSample2:iflow-Multicasting").projectDir = file("TestSample2/IntegrationFlow/Multicasting")

include "TestSample2:iflow-Content_Modifier_JSON"
project (":TestSample2:iflow-Content_Modifier_JSON").projectDir = file("TestSample2/IntegrationFlow/Content_Modifier_JSON")

include "TestSample2:iflow-Splitter2"
project (":TestSample2:iflow-Splitter2").projectDir = file("TestSample2/IntegrationFlow/Splitter2")

include "TestSample2:iflow-Aggregator_Palette"
project (":TestSample2:iflow-Aggregator_Palette").projectDir = file("TestSample2/IntegrationFlow/Aggregator_Palette")

include "TestSample2:iflow-postmanURL"
project (":TestSample2:iflow-postmanURL").projectDir = file("TestSample2/IntegrationFlow/postmanURL")

include "TestSample2:iflow-ContentModifier2"
project (":TestSample2:iflow-ContentModifier2").projectDir = file("TestSample2/IntegrationFlow/ContentModifier2")

include "TestSample2:iflow-Message_Mapping"
project (":TestSample2:iflow-Message_Mapping").projectDir = file("TestSample2/IntegrationFlow/Message_Mapping")

include "TestSample2:iflow-Using_Script_Collection"
project (":TestSample2:iflow-Using_Script_Collection").projectDir = file("TestSample2/IntegrationFlow/Using_Script_Collection")

include "TestSample2:iflow-splitter"
project (":TestSample2:iflow-splitter").projectDir = file("TestSample2/IntegrationFlow/splitter")

include "TestSample2:iflow-Content_Modifier_Practice"
project (":TestSample2:iflow-Content_Modifier_Practice").projectDir = file("TestSample2/IntegrationFlow/Content_Modifier_Practice")

include "TestSample2:vm-ProductType"
project (":TestSample2:vm-ProductType").projectDir = file("TestSample2/ValueMapping/ProductType")

include "TestSample2:iflow-Groovy_Trial2"
project (":TestSample2:iflow-Groovy_Trial2").projectDir = file("TestSample2/IntegrationFlow/Groovy_Trial2")

include "TestSample2:iflow-Router"
project (":TestSample2:iflow-Router").projectDir = file("TestSample2/IntegrationFlow/Router")

include "TestSample2:iflow-local_global"
project (":TestSample2:iflow-local_global").projectDir = file("TestSample2/IntegrationFlow/local_global")

include "TestSample2:iflow-exception_subprocess"
project (":TestSample2:iflow-exception_subprocess").projectDir = file("TestSample2/IntegrationFlow/exception_subprocess")

include "TestSample2:sc-Script_Library"
project (":TestSample2:sc-Script_Library").projectDir = file("TestSample2/ScriptCollection/Script_Library")

include "TestSample2:iflow-Converter"
project (":TestSample2:iflow-Converter").projectDir = file("TestSample2/IntegrationFlow/Converter")

include "TestSample2:iflow-Regex"
project (":TestSample2:iflow-Regex").projectDir = file("TestSample2/IntegrationFlow/Regex")

include "TestSample2:iflow-Property_Task1"
project (":TestSample2:iflow-Property_Task1").projectDir = file("TestSample2/IntegrationFlow/Property_Task1")

include "TestSample2:iflow-Scheduled_Timer"
project (":TestSample2:iflow-Scheduled_Timer").projectDir = file("TestSample2/IntegrationFlow/Scheduled_Timer")

include "TestSample2:iflow-Groovy_Trial1"
project (":TestSample2:iflow-Groovy_Trial1").projectDir = file("TestSample2/IntegrationFlow/Groovy_Trial1")

include "TestSample2:iflow-Mail_Adapter"
project (":TestSample2:iflow-Mail_Adapter").projectDir = file("TestSample2/IntegrationFlow/Mail_Adapter")

include "TestSample:iflow-Testcontentmodifier"
project (":TestSample:iflow-Testcontentmodifier").projectDir = file("TestSample/IntegrationFlow/Testcontentmodifier")

include "TestSample2:iflow-Regex_in_Contentmodifier"
project (":TestSample2:iflow-Regex_in_Contentmodifier").projectDir = file("TestSample2/IntegrationFlow/Regex_in_Contentmodifier")

include "TestSample2:iflow-Sample_iflow"
project (":TestSample2:iflow-Sample_iflow").projectDir = file("TestSample2/IntegrationFlow/Sample_iflow")

include "TestSample2:iflow-zipsplitter"
project (":TestSample2:iflow-zipsplitter").projectDir = file("TestSample2/IntegrationFlow/zipsplitter")

